/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view;

import br.com.transportadora.controller.RoteiroDiarioDuplicadoException;
import br.com.transportadora.controller.TransportadoraController;
import br.com.transportadora.model.Encomenda;
import br.com.transportadora.model.Motorista;
import br.com.transportadora.model.Veiculo;
import br.com.transportadora.view.dialogs.DialogCadMotorista;
import br.com.transportadora.view.dialogs.DialogCadVeiculo;
import br.com.transportadora.view.dialogs.DialogGerarRoteiro;
import br.com.transportadora.view.dialogs.DialogoCadEncomenda;
import java.time.LocalDate;
import javax.swing.JOptionPane;


/**
 *
 * @author hatachi
 */
public class JanelaPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form JanelaPrincipal
   */
  public JanelaPrincipal() {
    initComponents();
    //ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_small.png"));
    //setIconImage(img.getImage());
  }

  public void atualizarComponentes() {
    panelListaEncomendas1.atualizarListaEncomendas();
    panelListaMotoristas.atualizarListaMotoristas();
    panelListaRoteiros1.configurarListaRoteirosDiarios();
    panelListaVeiculos1.atualizarListaVeiculos();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    panelTabs = new javax.swing.JTabbedPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    panelListaMotoristas = new br.com.transportadora.view.panels.PanelListaMotoristas();
    jScrollPane2 = new javax.swing.JScrollPane();
    panelListaVeiculos1 = new br.com.transportadora.view.panels.PanelListaVeiculos();
    jScrollPane3 = new javax.swing.JScrollPane();
    panelListaEncomendas1 = new br.com.transportadora.view.panels.PanelListaEncomendas();
    jScrollPane4 = new javax.swing.JScrollPane();
    panelListaRoteiros1 = new br.com.transportadora.view.panels.PanelListaRoteiros();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Transportadora");
    getContentPane().setLayout(new java.awt.GridBagLayout());

    panelTabs.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        panelTabsFocusGained(evt);
      }
    });
    panelTabs.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        panelTabsMouseClicked(evt);
      }
    });

    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setViewportView(panelListaMotoristas);

    panelTabs.addTab("Motoristas", jScrollPane1);

    jScrollPane2.setViewportView(panelListaVeiculos1);

    panelTabs.addTab("Veículos", jScrollPane2);

    panelListaEncomendas1.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
    jScrollPane3.setViewportView(panelListaEncomendas1);

    panelTabs.addTab("Encomendas", jScrollPane3);

    jScrollPane4.setViewportView(panelListaRoteiros1);

    panelTabs.addTab("Roteiros", jScrollPane4);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(panelTabs, gridBagConstraints);

    jMenu1.setText("Cadastrar");

    jMenuItem1.setText("Veículo");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Motorista");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem2);

    jMenuItem3.setText("Encomenda");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem3);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Roteiros");

    jMenuItem4.setText("Gerar Roteiro Diário");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem4);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    setSize(new java.awt.Dimension(760, 630));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:
    DialogCadVeiculo dialog = new DialogCadVeiculo(this, true);
    dialog.setVisible(true);

    if (!dialog.isSalvo()) {
      return;
    }

    Veiculo veiculo = dialog.gerarVeiculo();
    TransportadoraController.getInstance().cadastrarVeiculo(veiculo);
    panelTabs.setSelectedIndex(1);
    atualizarComponentes();
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    // TODO add your handling code here:
    DialogCadMotorista dialogo = new DialogCadMotorista(this, true);
    dialogo.setVisible(true);

    if (!dialogo.isSalvo()) {
      return;
    }

    Motorista motorista = new Motorista();
    motorista.setNome(dialogo.getNome());
    motorista.setNascimento(dialogo.getNascimento());
    motorista.setEndereco(dialogo.getEndereco());
    motorista.setCnh(dialogo.getCnh());

    TransportadoraController.getInstance().cadastrarMotorista(motorista);
    panelTabs.setSelectedIndex(0);
    atualizarComponentes();
  }//GEN-LAST:event_jMenuItem2ActionPerformed

  private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    // TODO add your handling code here:
    DialogoCadEncomenda dialogo = new DialogoCadEncomenda(this, true);
    dialogo.setVisible(true);

    if (!dialogo.isSalvo()) {
      return;
    }

    Encomenda encomenda = dialogo.gerarEncomenda();
    TransportadoraController.getInstance().cadastrarEncomenda(encomenda);
    panelTabs.setSelectedIndex(2);
    atualizarComponentes();
  }//GEN-LAST:event_jMenuItem3ActionPerformed

  private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    // TODO add your handling code here:
    DialogGerarRoteiro dialogo = new DialogGerarRoteiro(this, true);
    dialogo.setVisible(true);

    if (!dialogo.isSalvo()) {
      return;
    }

    LocalDate data = dialogo.getData();
    try {
      TransportadoraController.getInstance().gerarRoteiroDiario(data);
    } catch (RoteiroDiarioDuplicadoException ex) {
      JOptionPane.showMessageDialog(null, "Já foi gerado um roteiro diário para essa data");
    }
    panelTabs.setSelectedIndex(3);
    atualizarComponentes();
  }//GEN-LAST:event_jMenuItem4ActionPerformed

  private void panelTabsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelTabsFocusGained
    // TODO add your handling code here:
    //atualizarComponentes();
  }//GEN-LAST:event_panelTabsFocusGained

    private void panelTabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTabsMouseClicked
    // TODO add your handling code here:
    atualizarComponentes();
    }//GEN-LAST:event_panelTabsMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new JanelaPrincipal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private br.com.transportadora.view.panels.PanelListaEncomendas panelListaEncomendas1;
  private br.com.transportadora.view.panels.PanelListaMotoristas panelListaMotoristas;
  private br.com.transportadora.view.panels.PanelListaRoteiros panelListaRoteiros1;
  private br.com.transportadora.view.panels.PanelListaVeiculos panelListaVeiculos1;
  private javax.swing.JTabbedPane panelTabs;
  // End of variables declaration//GEN-END:variables
}
