/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view.panels;

import br.com.transportadora.controller.TransportadoraController;
import br.com.transportadora.model.Encomenda;


/**
 *
 * @author hatachi
 */
public class PanelListaEncomendas extends javax.swing.JPanel {

  /**
   * Creates new form PanelListaEncomendas
   */
  public PanelListaEncomendas() {
    initComponents();
    atualizarListaEncomendas();
  }

  public void atualizarListaEncomendas() {
    removeAll();

    for (Encomenda encomenda : TransportadoraController.getInstance().listarEncomendas()) {
      PanelDetalheEncomenda detalheEncomenda = new PanelDetalheEncomenda();
      detalheEncomenda.atualizarInfoEncomenda(encomenda);
      add(detalheEncomenda);
    }

    repaint();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.GridLayout(0, 1, 10, 10));
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
