/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view.panels;

import br.com.transportadora.controller.TransportadoraController;
import br.com.transportadora.model.RoteiroDiario;
import java.util.List;
import javax.swing.DefaultListModel;


/**
 *
 * @author hatachi
 */
public class PanelListaRoteiros extends javax.swing.JPanel {

  List<RoteiroDiario> roteirosDiarios;

  /**
   * Creates new form PanelListaRoteiros
   */
  public PanelListaRoteiros() {
    initComponents();
    configurarListaRoteirosDiarios();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    listRoteirosDiarios = new javax.swing.JList<>();
    jButton1 = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    panelExibicaoRoteiros = new javax.swing.JPanel();
    panelDetalheRoteiroDiario1 = new br.com.transportadora.view.panels.PanelDetalheRoteiroDiario();

    setLayout(new java.awt.GridBagLayout());

    jPanel1.setMinimumSize(new java.awt.Dimension(100, 20));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Roteiros");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.weightx = 1.0;
    jPanel1.add(jLabel1, gridBagConstraints);

    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 200));
    jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 200));

    listRoteirosDiarios.setMinimumSize(new java.awt.Dimension(100, 200));
    listRoteirosDiarios.setPreferredSize(new java.awt.Dimension(100, 200));
    listRoteirosDiarios.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        listRoteirosDiariosMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(listRoteirosDiarios);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
    jPanel1.add(jScrollPane1, gridBagConstraints);

    jButton1.setText("Fechar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(jButton1, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    add(jPanel1, gridBagConstraints);

    jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    add(jSeparator1, gridBagConstraints);

    panelExibicaoRoteiros.setLayout(new java.awt.BorderLayout());
    panelExibicaoRoteiros.add(panelDetalheRoteiroDiario1, java.awt.BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    add(panelExibicaoRoteiros, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void listRoteirosDiariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRoteirosDiariosMouseClicked
    // TODO add your handling code here:
    RoteiroDiario roteiroDiarioSelecionado = listRoteirosDiarios.getSelectedValue();

    if (roteiroDiarioSelecionado == null) {
      return;
    }
    panelDetalheRoteiroDiario1.setVisible(true);
    panelDetalheRoteiroDiario1.configurarInformacoes(roteiroDiarioSelecionado);
  }//GEN-LAST:event_listRoteirosDiariosMouseClicked

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    panelDetalheRoteiroDiario1.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JList<br.com.transportadora.model.RoteiroDiario> listRoteirosDiarios;
  private br.com.transportadora.view.panels.PanelDetalheRoteiroDiario panelDetalheRoteiroDiario1;
  private javax.swing.JPanel panelExibicaoRoteiros;
  // End of variables declaration//GEN-END:variables

  public void configurarListaRoteirosDiarios() {
    listRoteirosDiarios.removeAll();
    this.roteirosDiarios = TransportadoraController.getInstance().listarRoteirosDiarios();
    this.listRoteirosDiarios.setModel(listModelRoteiroDiario());
  }

  private DefaultListModel<RoteiroDiario> listModelRoteiroDiario() {
    DefaultListModel<RoteiroDiario> listModel = new DefaultListModel<>();
    for (RoteiroDiario roteiroDiario : roteirosDiarios) {
      listModel.add(0, roteiroDiario);
    }
    return listModel;
  }

}
