package br.com.transportadora.view.panels;

import br.com.transportadora.model.Motorista;
import java.time.format.DateTimeFormatter;


public class PanelDetalheMotorista extends javax.swing.JPanel {

  private Motorista motorista;

  /**
   * Creates new form PanelDetalheMotorista
   */
  public PanelDetalheMotorista() {
    initComponents();
  }

  public void atualizarInfoMotorista(Motorista motorista) {
    this.motorista = motorista;
    lblNome.setText(this.motorista.getNome());
    lblNascimento.setText(this.motorista.getNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
    panelDetalheCnh1.atualizarInfoCnh(this.motorista.getCnh());
    panelDetalheEndereco1.atualizarInfoEndereco(this.motorista.getEndereco());
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    lblNome = new javax.swing.JLabel();
    lblNascimento = new javax.swing.JLabel();
    panelDetalheEndereco1 = new br.com.transportadora.view.panels.PanelDetalheEndereco();
    panelDetalheCnh1 = new br.com.transportadora.view.panels.PanelDetalheCnh();

    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    setLayout(new java.awt.GridBagLayout());

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/motorista.png"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel1, gridBagConstraints);

    jLabel2.setText("Nome");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel2, gridBagConstraints);

    jLabel3.setText("Nascimento");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel3, gridBagConstraints);

    lblNome.setText("jLabel5");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(lblNome, gridBagConstraints);

    lblNascimento.setText("jLabel4");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(lblNascimento, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(panelDetalheEndereco1, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(panelDetalheCnh1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel lblNascimento;
  private javax.swing.JLabel lblNome;
  private br.com.transportadora.view.panels.PanelDetalheCnh panelDetalheCnh1;
  private br.com.transportadora.view.panels.PanelDetalheEndereco panelDetalheEndereco1;
  // End of variables declaration//GEN-END:variables

}
