/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view.panels;


/**
 *
 * @author hatachi
 */
public class panelCadVeiculo extends javax.swing.JPanel {

  /**
   * Creates new form panelCadVeiculo
   */
  public panelCadVeiculo() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    inputMarca = new javax.swing.JTextField();
    inputModelo = new javax.swing.JTextField();
    inputAno = new javax.swing.JSpinner();
    inputPlaca = new javax.swing.JTextField();
    inputTipo = new javax.swing.JComboBox<>();
    lblIcon = new javax.swing.JLabel();
    btnSalvar = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Marca");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jLabel1, gridBagConstraints);

    jLabel2.setText("Modelo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jLabel2, gridBagConstraints);

    jLabel3.setText("Ano");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jLabel3, gridBagConstraints);

    jLabel4.setText("Placa");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jLabel4, gridBagConstraints);
    add(jLabel6, new java.awt.GridBagConstraints());

    jLabel5.setText("Tipo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(jLabel5, gridBagConstraints);

    inputMarca.setMinimumSize(new java.awt.Dimension(120, 23));
    inputMarca.setPreferredSize(new java.awt.Dimension(120, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(inputMarca, gridBagConstraints);

    inputModelo.setMinimumSize(new java.awt.Dimension(120, 23));
    inputModelo.setPreferredSize(new java.awt.Dimension(120, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(inputModelo, gridBagConstraints);

    inputAno.setModel(new javax.swing.SpinnerNumberModel(2005, 1900, null, 1));
    inputAno.setMinimumSize(new java.awt.Dimension(80, 26));
    inputAno.setPreferredSize(new java.awt.Dimension(80, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(inputAno, gridBagConstraints);

    inputPlaca.setMinimumSize(new java.awt.Dimension(120, 23));
    inputPlaca.setPreferredSize(new java.awt.Dimension(120, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(inputPlaca, gridBagConstraints);

    inputTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    inputTipo.setMinimumSize(new java.awt.Dimension(120, 25));
    inputTipo.setPreferredSize(new java.awt.Dimension(120, 25));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(inputTipo, gridBagConstraints);

    lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caminhao-bau.png"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(lblIcon, gridBagConstraints);

    btnSalvar.setText("Salvar");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btnSalvar, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSalvar;
  private javax.swing.JSpinner inputAno;
  private javax.swing.JTextField inputMarca;
  private javax.swing.JTextField inputModelo;
  private javax.swing.JTextField inputPlaca;
  private javax.swing.JComboBox<String> inputTipo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel lblIcon;
  // End of variables declaration//GEN-END:variables
}
