package br.com.transportadora.view.panels;

import br.com.transportadora.model.CaminhaoBau;
import br.com.transportadora.model.Carreta;
import br.com.transportadora.model.Van;
import br.com.transportadora.model.Veiculo;


public class PanelDetalheVeiculo extends javax.swing.JPanel {

  private Veiculo veiculo;

  /**
   * Creates new form PanelDetalheVeiculo
   */
  public PanelDetalheVeiculo() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel5 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    outputMarca = new javax.swing.JLabel();
    outputModelo = new javax.swing.JLabel();
    outputAno = new javax.swing.JLabel();
    outputPlaca = new javax.swing.JLabel();
    outputCNH = new javax.swing.JLabel();
    outputIcon = new javax.swing.JLabel();

    jLabel5.setText("jLabel5");

    jLabel15.setText("jLabel15");

    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Marca:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel1, gridBagConstraints);

    jLabel2.setText("Modelo:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel2, gridBagConstraints);

    jLabel3.setText("Ano:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel3, gridBagConstraints);

    jLabel4.setText("Placa:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel4, gridBagConstraints);

    jLabel6.setText("Classe CNH:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(jLabel6, gridBagConstraints);

    outputMarca.setText("marca");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(outputMarca, gridBagConstraints);

    outputModelo.setText("modelo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(outputModelo, gridBagConstraints);

    outputAno.setText("ano");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(outputAno, gridBagConstraints);

    outputPlaca.setText("placa");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(outputPlaca, gridBagConstraints);

    outputCNH.setText("cnh");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(outputCNH, gridBagConstraints);

    outputIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/van.png"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(outputIcon, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel outputAno;
  private javax.swing.JLabel outputCNH;
  private javax.swing.JLabel outputIcon;
  private javax.swing.JLabel outputMarca;
  private javax.swing.JLabel outputModelo;
  private javax.swing.JLabel outputPlaca;
  // End of variables declaration//GEN-END:variables

  public void atualizarInfoVeiculo(Veiculo veiculo) {
    this.veiculo = veiculo;
    outputAno.setText(veiculo.getAno().toString());
    outputMarca.setText(veiculo.getMarca());
    outputModelo.setText(veiculo.getModelo());
    outputCNH.setText(veiculo.getCnhMinima().toString());

    if (veiculo instanceof CaminhaoBau) {
      outputIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caminhao-bau.png")));
    } else if (veiculo instanceof Carreta) {
      outputIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carreta.png")));
    } else if (veiculo instanceof Van) {
      outputIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/van.png")));
    }
  }
}
