/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view.panels;

import br.com.transportadora.controller.TransportadoraController;
import br.com.transportadora.model.Veiculo;


/**
 *
 * @author hatachi
 */
public class PanelListaVeiculos extends javax.swing.JPanel {

  /**
   * Creates new form PanelListaVeiculos
   */
  public PanelListaVeiculos() {
    initComponents();
    atualizarListaVeiculos();
  }

  public void atualizarListaVeiculos() {
    removeAll();

    for (Veiculo veiculo : TransportadoraController.getInstance().listarVeiculos()) {
      PanelDetalheVeiculo detalheVeiculo = new PanelDetalheVeiculo();
      detalheVeiculo.atualizarInfoVeiculo(veiculo);
      add(detalheVeiculo);
    }

    repaint();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.GridLayout(0, 4, 10, 10));
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
