/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view.panels;

import br.com.transportadora.model.Cnh;


/**
 *
 * @author hatachi
 */
public class PanelDetalheCnh extends javax.swing.JPanel {

  private Cnh cnh;

  /**
   * Creates new form PanelDetalheCnh
   */
  public PanelDetalheCnh() {
    initComponents();
  }

  public void atualizarInfoCnh(Cnh cnh) {
    this.cnh = cnh;
    lblNro.setText(this.cnh.getNumero());
    lblTipo.setText(this.cnh.getClasse().toString());
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lblNro = new javax.swing.JLabel();
    lblTipo = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createTitledBorder("CNH"));
    setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Número");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 10);
    add(jLabel1, gridBagConstraints);

    jLabel2.setText("Tipo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 10);
    add(jLabel2, gridBagConstraints);

    lblNro.setText("nro");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(lblNro, gridBagConstraints);

    lblTipo.setText("tipo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    add(lblTipo, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel lblNro;
  private javax.swing.JLabel lblTipo;
  // End of variables declaration//GEN-END:variables

}
