package br.com.transportadora.view.panels;

import br.com.transportadora.controller.TransportadoraController;
import br.com.transportadora.model.Motorista;


public class PanelListaMotoristas extends javax.swing.JPanel {

  /**
   * Creates new form PanelListaMotoristas
   */
  public PanelListaMotoristas() {
    initComponents();
    atualizarListaMotoristas();
  }

  public void atualizarListaMotoristas() {
    removeAll();

    for (Motorista motorista : TransportadoraController.getInstance().listarMotoristas()) {
      PanelDetalheMotorista detalheMotorista = new PanelDetalheMotorista();
      detalheMotorista.atualizarInfoMotorista(motorista);
      add(detalheMotorista);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 3, 5, 5));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
