/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view.dialogs;

import br.com.transportadora.model.Cnh;
import br.com.transportadora.model.Endereco;
import java.time.LocalDate;
import java.time.ZoneId;


/**
 *
 * @author hatachi
 */
public class DialogCadMotorista extends javax.swing.JDialog {

  private boolean salvo = false;

  /**
   * Creates new form DialogCadMotorista
   */
  public DialogCadMotorista(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  public boolean isSalvo() {
    return salvo;
  }

  public String getNome() {
    return inputNome.getText();
  }

  public LocalDate getNascimento() {
    LocalDate localDate = inputNascimento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

    return localDate;
  }

  public Endereco getEndereco() {
    return panelCadEndereco1.gerarEndereco();
  }

  public Cnh getCnh() {
    return panelCadCnh1.gerarCnh();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    lblIcon = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    inputNome = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    inputNascimento = new org.jdesktop.swingx.JXDatePicker();
    panelCadEndereco1 = new br.com.transportadora.view.panels.PanelCadEndereco();
    panelCadCnh1 = new br.com.transportadora.view.panels.PanelCadCnh();
    btnSalvar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastrar Motorista");
    setAlwaysOnTop(true);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/motorista.png"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(lblIcon, gridBagConstraints);

    jLabel1.setText("Nome");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    getContentPane().add(jLabel1, gridBagConstraints);

    inputNome.setMinimumSize(new java.awt.Dimension(120, 23));
    inputNome.setPreferredSize(new java.awt.Dimension(120, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(inputNome, gridBagConstraints);

    jLabel2.setText("Nascimento");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    getContentPane().add(jLabel2, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(inputNascimento, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    getContentPane().add(panelCadEndereco1, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(panelCadCnh1, gridBagConstraints);

    btnSalvar.setText("Salvar");
    btnSalvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalvarActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(btnSalvar, gridBagConstraints);

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    // TODO add your handling code here:
    salvo = true;
    dispose();
  }//GEN-LAST:event_btnSalvarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSalvar;
  private org.jdesktop.swingx.JXDatePicker inputNascimento;
  private javax.swing.JTextField inputNome;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel lblIcon;
  private br.com.transportadora.view.panels.PanelCadCnh panelCadCnh1;
  private br.com.transportadora.view.panels.PanelCadEndereco panelCadEndereco1;
  // End of variables declaration//GEN-END:variables
}
