package br.com.transportadora.view.dialogs;

import br.com.transportadora.model.Destinatario;
import br.com.transportadora.model.Encomenda;
import br.com.transportadora.model.Remetente;
import java.time.ZoneId;


public class DialogoCadEncomenda extends javax.swing.JDialog {

  private boolean salvo;

  /**
   * Creates new form DialogCadEncomenda
   */
  public DialogoCadEncomenda(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    inputNomeRemetente = new javax.swing.JTextField();
    panelCadEnderecoRemetente = new br.com.transportadora.view.panels.PanelCadEndereco();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    inputNomeDestinatario = new javax.swing.JTextField();
    panelCadEnderecoDestinatario = new br.com.transportadora.view.panels.PanelCadEndereco();
    jPanel3 = new javax.swing.JPanel();
    inputDataDeposito = new org.jdesktop.swingx.JXDatePicker();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    inputCodLocalizador = new javax.swing.JTextField();
    inputPeso = new javax.swing.JSpinner();
    btnSalvar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastrar Encomenda");
    setAlwaysOnTop(true);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Remetente"));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Nome");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel1.add(jLabel1, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(inputNomeRemetente, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(panelCadEnderecoRemetente, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(jPanel1, gridBagConstraints);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Destinatário"));
    jPanel2.setLayout(new java.awt.GridBagLayout());

    jLabel2.setText("Nome");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
    jPanel2.add(jLabel2, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel2.add(inputNomeDestinatario, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel2.add(panelCadEnderecoDestinatario, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(jPanel2, gridBagConstraints);

    jPanel3.setLayout(new java.awt.GridBagLayout());

    inputDataDeposito.setMinimumSize(new java.awt.Dimension(200, 23));
    inputDataDeposito.setPreferredSize(new java.awt.Dimension(200, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel3.add(inputDataDeposito, gridBagConstraints);

    jLabel3.setText("Data do depósito");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel3.add(jLabel3, gridBagConstraints);

    jLabel4.setText("Peso do objeto");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel3.add(jLabel4, gridBagConstraints);

    jLabel5.setText("Código localizador");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel3.add(jLabel5, gridBagConstraints);

    inputCodLocalizador.setMinimumSize(new java.awt.Dimension(200, 23));
    inputCodLocalizador.setPreferredSize(new java.awt.Dimension(200, 23));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel3.add(inputCodLocalizador, gridBagConstraints);

    inputPeso.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, null, 1.0d));
    inputPeso.setMinimumSize(new java.awt.Dimension(100, 26));
    inputPeso.setPreferredSize(new java.awt.Dimension(100, 26));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel3.add(inputPeso, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 1.0;
    getContentPane().add(jPanel3, gridBagConstraints);

    btnSalvar.setText("Salvar");
    btnSalvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalvarActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(btnSalvar, gridBagConstraints);

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    // TODO add your handling code here:
    salvo = true;
    dispose();
  }//GEN-LAST:event_btnSalvarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSalvar;
  private javax.swing.JTextField inputCodLocalizador;
  private org.jdesktop.swingx.JXDatePicker inputDataDeposito;
  private javax.swing.JTextField inputNomeDestinatario;
  private javax.swing.JTextField inputNomeRemetente;
  private javax.swing.JSpinner inputPeso;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private br.com.transportadora.view.panels.PanelCadEndereco panelCadEnderecoDestinatario;
  private br.com.transportadora.view.panels.PanelCadEndereco panelCadEnderecoRemetente;
  // End of variables declaration//GEN-END:variables

  public boolean isSalvo() {
    return salvo;
  }

  public Encomenda gerarEncomenda() {
    Encomenda encomenda = new Encomenda();

    Remetente remetente = new Remetente(inputNomeRemetente.getText(), panelCadEnderecoRemetente.gerarEndereco());
    Destinatario destinatario = new Destinatario(inputNomeDestinatario.getText(), panelCadEnderecoDestinatario.gerarEndereco());

    encomenda.setDestinatario(destinatario);
    encomenda.setRemetente(remetente);
    encomenda.setPeso(((Number) inputPeso.getValue()).doubleValue());
    encomenda.setCodigo(inputCodLocalizador.getText());
    encomenda.setDataCadastro(inputDataDeposito.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
    return encomenda;
  }
}
