/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.transportadora.view.dialogs;


/**
 *
 * @author hatachi
 */
public class DialogoCadEncomenda extends javax.swing.JDialog {

  /**
   * Creates new form DialogCadEncomenda
   */
  public DialogoCadEncomenda(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelCadEncomenda1 = new br.com.transportadora.view.panels.PanelCadEncomenda();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cadastrar Encomenda");
    setAlwaysOnTop(true);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    panelCadEncomenda1.setToolTipText("");
    getContentPane().add(panelCadEncomenda1, new java.awt.GridBagConstraints());

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private br.com.transportadora.view.panels.PanelCadEncomenda panelCadEncomenda1;
  // End of variables declaration//GEN-END:variables
}
